### PR TITLE
use target_include_directories

### PR DESCRIPTION
**Pull request by Karsten1987**
thanks @jonbinney for merging #54 
This is simple a backport of the same commit onto the eloquent branch. I would very much appreciate to see this patch being backported and released into eloquent.

Signed-off-by: Karsten Knese <karsten@openrobotics.org>

### CODE REVIEW

**Comment by Karsten1987** [comment]
I don't run CI on this as I think it's fair to rely on the PR job which came back green with all tests passed.

**Review by jonbinney — APPROVED** [review]
LGTM

**Comment by Karsten1987** [comment]
Do you think you could cut an eloquent release for this?

**Comment by jonbinney** [comment]
I created the changelog and bumped the version on the eloquent branch in this repo, but i don't have push permissions for the ros2 release repo to do the release. @wjwwood could you give me write access to https://github.com/ros2-gbp/laser_geometry-release ?

**Comment by wjwwood** [comment]
@jonbinney I've added you, but you have to accept the invitation first.

**Comment by wjwwood** [comment]
I have given you the ⚡️.

**Comment by jonbinney** [comment]
Thanks @wjwwood ! @Karsten1987 I've made the release: https://github.com/ros/rosdistro/pull/23691

**Pull request merged**
