### PR TITLE
use ament_export_targets()

### PR DESCRIPTION
**Pull request by dirk-thomas**
Related to ament/ament_cmake#237.

### CODE REVIEW

**Review by jonbinney — APPROVED** [review]
LGTM

**Comment by dirk-thomas** [comment]
Merging this without the other referenced PRs broke the build...

**Comment by jonbinney** [comment]
@dirk-thomas what other PRs need to be merged for this  to work? The link in the description is for an issue, not another PR. Would you like me to revert it?

**Comment by dirk-thomas** [comment]
As you can see in the referenced issue all related pull requests have been merged now.

**Comment by jonbinney** [comment]
Great!

**Pull request merged**
