### PR TITLE
Deprecating tf2 C Headers

### PR DESCRIPTION
**Pull request by CursedRock17**
Related to this [pull request](https://github.com/ros2/geometry2/pull/720) in `geometry2` in which we deprecated the `.h` style headers in favor of `.hpp`.

Edit: I should mention this is meant to be a preemptive PR for if/when the related pull request gets approved. I'm also working on a backport so there won't be distribution issues

### CODE REVIEW

**Comment by clalancette** [comment]
@CursedRock17 I retargeted this at the `rolling` branch, and this now needs a rebase.

**Comment by CursedRock17** [comment]
A bit wonkey but it seems to like the rebase.

**Comment by clalancette** [comment]
Pulls: https://github.com/ros2/geometry2/pull/720, https://github.com/ros2/rviz/pull/1289, https://github.com/ros-perception/laser_geometry/pull/98
Gist: https://gist.githubusercontent.com/clalancette/b83127091186f2489c09c4c787585861/raw/3c16fd56b4d645d09b9cadf800da79cbfd1acbaf/ros2.repos
BUILD args: 
TEST args: 
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/14792
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/22096/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/16353/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/1616/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/22837/)

**Comment by ahcorde** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/22286/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/16546/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/1813/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/23075/)

**Review by ahcorde — APPROVED** [review]

**Pull request merged**
