### PR TITLE
Fix pointcloud2 projections

### PR DESCRIPTION
**Pull request by roehling**
The LaserProjection class had a few bugs when working with sensor_msgs::PointCloud2 messages.

### CODE REVIEW

**Comment by vrabaud** [comment]
@hershwg  , I don't want to overstep your duties, will you merge that one ? Thx.

**Comment by hersh** [comment]
@vrabaud don't worry about overstepping. :)

**Comment by roehling** [comment]
Will the fixes be backported to Groovy as well?

**Comment by hersh** [comment]
If you make a pull request and test it, I will merge it.

**Comment by vrabaud** [comment]
I just cherry-picked it. @hersh  you probably want to release groovy/hydro (hydro actually has some fixes that have not been pushed yet)

**Comment by hershwg** [comment]
@vrabaud I would be happy to hand off maintainer-ship of this package to you, if you would like.

**Comment by hershwg** [comment]
OK I have now released the changes into hydro in version 1.5.14.

However I don't actually see a clear way to release into Groovy for this package.  When the first Hydro release was done, the minor version number was not changed, only the "patch" version number.  The version number format is "major.minor.patch", so latest hydro I just released is major=1, minor=5, patch=14.  The latest Groovy version is 1.5.9.  Version 1.5.10 was the first hydro version.  Therefore what version number should the next Groovy version use?   I'm sure there is a solution with re-releasing hydro as 1.6.0 and groovy as 1.5.15 or something, but it's not yet clear to me if bumping the minor version number within a release will cause any trouble.

**Comment by vrabaud** [comment]
@hershwg  , I'm already maintaining 52 packages so I'm good :)
For releasing into Groovy, that is problematic indeed. If the API was not changed, 1.5.14 could be released for Groovy no ?

**Comment by hersh** [comment]
That's not a bad idea.  I'll look over the changes from 1.5.9 to 1.5.14 and see if they are all suitable for groovy.

**Comment by roehling** [comment]
There are no C++ API changes between 1.5.9 and 1.5.14.
The changes between hydro-devel and groovy-devel are:

A few missing run_depends have been added to package.xml, which should be fine for Groovy as well.

The buildtool_depend requires at least catkin 0.5.68 now; Groovy ships with catkin 0.5.77, so that's not an issue.

The FindEigen.cmake is no longer shipped with the package; catkin 0.5.77 provides that module, so again not an issue.

The CATKIN_ENABLE_TESTING switch is honored now; supported since catkin 0.5.68, another non-issue.

**Comment by hersh** [comment]
@roehling excellent, thanks.

**Comment by hersh** [comment]
OK, I just released 1.5.14 into groovy.

**Pull request merged**
