### PR TITLE
Require C++11

### PR DESCRIPTION
**Pull request by peci1**
Trying to fix kinetic.

### CODE REVIEW

**Comment by peci1** [comment]
All green :)

**Review by mabelzhang — APPROVED** [review]
Thanks! Looks good. Hopefully it passes Kdev too!

**Comment by mabelzhang** [comment]
Let's see if the next job is green here, then I'll run another round of releases
https://build.ros.org/view/Kdev/job/Kdev__laser_geometry__ubuntu_xenial_amd64/

**Comment by mabelzhang** [comment]
Will be out in the next Melodic sync after approval
https://github.com/ros/rosdistro/pull/28247

**Pull request merged**
