### PR TITLE
Drop CMake extras redundant with eigen3_cmake_module

### PR DESCRIPTION
**Pull request by hidmic**
Precisely what the title says. Said extras were redundant with `eigen3_cmake_module` and caused trouble in downstream packages.

### CODE REVIEW

**Review by sloretz — APPROVED** [review]

**Comment by hidmic** [comment]
CI up to `tf2_sensor_msgs`, `laser_geometry` and above:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/8986/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/4753/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/7357/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/8918/)

**Comment by hidmic** [comment]
This one's ready to go. Who'd be the right person to do so?

**Comment by wjwwood** [comment]
@jonbinney do you want to look first, or can I merge?

**Review by wjwwood — APPROVED** [review]

**Comment by jonbinney** [comment]
@wjwwood LGTM, feel free to merge.

**Pull request merged**
