### PR TITLE
export dll on Windows

### PR DESCRIPTION
**Pull request by kejxu**
`RUNTIME DESTINATION` needs to be added to export `.dll` on Windows

### CODE REVIEW

**Comment by jonbinney** [comment]
Thanks @kejxu ! What ROS distros have you tried this on? Have you run it on linux to make sure it didn't break the build there?

**Comment by kejxu** [comment]
> What ROS distros have you tried this on? Have you run it on linux to make sure it didn't break the build there?

Thanks for the input @jonbinney! We have been working on melodic, and yes we have tested this change on Ubuntu 18.04.

Reasons why we don't need to worry about this change:
- `LIBRARY DESTINATION ${CATKIN_PACKAGE_LIB_DESTINATION}` is used for `.so` files on Linux; `RUNTIME DESTINATION ${CATKIN_GLOBAL_BIN_DESTINATION}` only affects `.dll` files on Windows, has no effect on Linux's shared libraries
- this changes is recommended in `catkin`'s [instructions](http://docs.ros.org/melodic/api/catkin/html/howto/format2/building_libraries.html)

**Comment by jonbinney** [comment]
Sounds good. I'll go ahead and merge these 2 PRs; I assume https://github.com/ros-perception/laser_geometry/pull/42 needs to be merged first?

**Comment by kejxu** [comment]
> Sounds good. I'll go ahead and merge these 2 PRs; I assume #42 needs to be merged first?

Thanks! there wouldn't be too much of a difference, #42 only affects symbols' visibility, would not cause any build break; as long as both of these two are checked in, they would work fine =)

**Pull request merged**
