### PR TITLE
Polish ros2 branch

### PR DESCRIPTION
**Pull request by botteroa-si**
Make the branch work on Windows (with VS '15 and '17), macOS and Linux.

- Remove PoinCloud support: for now only supports PointCloud2. 
- Remove Boost dependencies
- Make tests work (when possible: the other tests need tf2)
- Introduce and fix ament linters present in most ROS2 packages (cpplint, uncrustify, cmake_lint, cppcheck)
- Fix all Windows warnings on OSRF Jenkins warning level
- Build as static library for now

### CODE REVIEW

**Comment by botteroa-si** [comment]
CI:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/4102/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/1192/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/3397/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/4206/)

**Comment by botteroa-si** [comment]
The CI instability seems to be unrelated to our changes to laser_geometry.

**Comment by greimela-si** [comment]
This pull request is required to migrate the LaserScan display to RViz2 (https://github.com/ros2/rviz/issues/79).

**Comment by wjwwood** [comment]
> Remove PoinCloud support: for now only supports PointCloud2.

This is a fine shortcut to take, but after merging please make an issue for this, and when I review the code I'll look for a TODO to match.

> Make tests work (when possible: the other tests need tf2)

Why is needing `tf2` a problem?

> Introduce and fix ament linters present in most ROS2 packages (cpplint, uncrustify, cmake_lint, cppcheck)

This, along with some other changes like the `.h` being changed to `.hpp` are not required to be in ROS 2, and though I chose to do this in rviz, I'd like to point out that they're not required.

> Build as static library for now

If this is a shortcut to avoid visibility macros, I'd rather not delay this. It will need to be used as a shared library at some point in the future, I'd rather see that done now.

----

What about the python code? I think it depends on missing python code in `sensor_msgs`.

I'd say it's fine not do everything in one pull requests, but we should do them soon or find someone willing to maintain this package in ROS 2 (I don't @vrabaud is going to have time) so that they can do these follow up items and/or accept contributions when someone does port those things for us in a pull request.

I don't have time to take on that role.

**Comment by wjwwood** [comment]
@jonbinney I don't want to put you on the spot, but I will 😄, are you interested in helping maintain the ros2 branch of this?

----

If so, do you have an opinion on whether we should:

- make style changes on the ros2 branch at will
- avoid style changes on the ros2 branch to keep it close to indigo-devel
- make style changes on ros2 branch and backport them to melodic-devel to keep them close, but up-to-date

**Comment by jonbinney** [comment]
@wjwwood sure, I'll maintain the ros2 branch. I like the third option you mentioned: make style changes on the ros2 branch and backport them to melodic. Hopefully there won't be many changes for ROS1 distros prior to melodic.

@botteroa-si after you respond to @wjwwood 's comments, I'll take another pass through this.

**Comment by greimela-si** [comment]
@wjwwood @jonbinney 
> This is a fine shortcut to take, but after merging please make an issue for this, and when I review the code I'll look for a TODO to match.

Alright, we'll add a TODO to the code and an issue to the repository.

> Why is needing `tf2` a problem?

The disabled tests currently fail due to `lookupTransform()` failing.
They require a published transform to "laser_frame" in order to work, which is currently not available in the tests.

By the way, shouldn't the transform from "laser_frame" to "laser_frame" always be available, even if it is not explicitly published? This is currently not the case.

> This, along with some other changes like the `.h` being changed to `.hpp` are not required to be in ROS 2, and though I chose to do this in rviz, I'd like to point out that they're not required.

Good to know. 
We still prefer keeping the rules since they make the code more readable and concise.

> If this is a shortcut to avoid visibility macros, I'd rather not delay this. It will need to be used as a shared library at some point in the future, I'd rather see that done now.

Yes, it is in fact to avoid using visibility macros.
This is mainly due to process reasons that don't allow us to add third party code to this repository in a timely manner.
If one of you could commit the visibility_control headers to our branch we can continue from there (e.g. from https://github.com/ros2/rclcpp/blob/master/rclcpp/include/rclcpp/visibility_control.hpp).

**Comment by jonbinney** [comment]
I'll take a look at this PR tomorrow.

**Comment by jonbinney** [comment]
@greimela-si i don't have permissions to push directly to the branch for this PR that is in @botteroa-si 's fork, but I made a PR: https://github.com/bsinno/laser_geometry/pull/1
Or  if that doesn't work I can add it to the ROS2 branch here (is that what you meant)?

**Comment by greimela-si** [comment]
@jonbinney 
We have "Allow edits from maintainers" enabled on this pull request. 
So if I understand it correctly you should be able to directly push commits to our branch.

I'm currently not sure about the pull request approach, so directly adding the file to the ros2 branch is fine.

**Comment by jonbinney** [comment]
@greimela-si @botteroa-si I went ahead and added the header directly to the ros2 branch: https://github.com/ros-perception/laser_geometry/pull/31

**Comment by Martin-Idel-SI** [comment]
Thanks for the visibility control. 

The package is now build as shared library. We also added the comment regarding PointCloud support. There already was a comment for why tests for the function "transformLaserScanToPointCloud2" can't run.
Here is a CI run:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/4149/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/1226/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/3430/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/4253/)

**Comment by botteroa-si** [comment]
The instability of Windows is unrelated to our changes, while the instability of the macOS build was due to the fact that the tests take a longer time on Mac, greater than the default timeout. We have now increased the timeout, and here's the new CI run:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/4150/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/1229/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/3431/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/4254/)

**Comment by botteroa-si** [comment]
@wjwwood, @jonbinney, 
as said, the instability of the Windows one is unrelated to our changes. Therefore we believe that now it is ready to be merged.

**Comment by jonbinney** [comment]
Looks good, merging. Thanks @botteroa-si !

**Pull request merged**
