### PR TITLE
Added new method projectLaserToPC1 in laser_geometry.py that returns a PointCloud1

### PR DESCRIPTION
**Pull request by 2scholz**
The new method returns a `sensor_msgs/PointCloud`, in contrast to the `projectLaser` method which returns a `sensor_msgs/PointCloud2`.

We use this package in an undergraduate course at our university and leave it to the students whether they implement their code in C++ or Python.
The students using Python struggled quite a bit with the PointCloud2 that is returned by the current interfaces.
`sensor_msgs/PointCloud` is a lot easier to handle for beginners.

### CODE REVIEW

**Comment by v4hn** [comment]
@wjwwood @vrabaud Please have a look at this. It would be great if we could have this synced in kinetic (maybe even indigo? It's API compatible...) to use it in our next winter term.

**Comment by wjwwood** [comment]
@vrabaud do you have time?

**Comment by vrabaud** [comment]
I'd be pretty reluctant at merging something that includes PointCloud1 and also transforms in Python (which are therefore slow).
@2scholz , what problem do your students have with  https://github.com/ros/common_msgs/blob/jade-devel/sensor_msgs/src/sensor_msgs/point_cloud2.py#L60 ? I'd rather fix the API/docs there.

**Comment by v4hn** [comment]
> I'd be pretty reluctant at merging something that includes PointCloud1 and also transforms in Python

Why? The C++ interface provides methods for both message types.
I believe the Python interface should provide the same functionality as C++.

We tell our students they can do their whole project in C++ or Python and it is not very convenient to tell them later on that they have to jump through extra hoops to get there...

If a user turns to Python for something like data conversion, they already know what they're in for, in terms of performance.

The difference is basically between:
```
cloud= lp.projectLaserToPC1(scan)
print cloud.points
```
and
```
cloud= lp.projectLaser(scan)
points= [p for p in read_points(cloud, ["x", "y", "z"])]
print points
```
During a previous course I noticed the latter has more pitfalls than necessary for people new to ROS/robotics. 

- The generator expression is needed if you want to have the data as one indexed list (more students know how to work with lists than with generator expressions).

- The explicit field description is required because otherwise I get a trailing 0 over here for each point (the xyz padding value?), and I'm not even sure it's guaranteed to put xyz as the first three channels without it.

- The resulting datastructure can not be indexed by axis-letter, i.e. `points[0].x`, but by field index, `points[0][0]`. This is less intuitive and not helpful when they just try to get their head around coordinate transforms for the first time.

**Comment by wjwwood** [comment]
I don't mind one way or the other. PointCloud is deprecated, but realistically will most likely never be removed in ROS 1.

I'm not the maintainer of this, so I'll leave it up to you guys to sort out.

**Comment by v4hn** [comment]
> I'm not the maintainer of this

? According to the package.xml you are. This is why I pinged you in the first place.

**Comment by wjwwood** [comment]
Oh... well I didn't know that 😄. I guess I probably threw my name in there when it was orphaned. Either way, I'm at most a "caretaker" type of maintainer. I will do releases and stuff, but I need someone else to take over on the pr's and issues.

**Comment by v4hn** [comment]
@vrabaud please notice that @2scholz works in my lab as a student assistant.
He worked on this because I asked him to.

**Comment by vrabaud** [comment]
Hi, so it LGTM but I'd rather fix the problems you mention upstream in sensor_msgs: that would help other packages and limit maintenance on laser_geometry.
Also, overall, I've tried to limit the maintenance of Python + C++ code by wrapping the C++ with Boost Python (e.g. in vision_opencv).
Here is what I propose to tackle your problems (I can only get to it in 10 days, sorry):
- in sensor_msgs, create a function to read a PointCloud2 by returning an object with the proper fields (that would tackle your problem 3)
- a ctype.Union should actually have the same effect and solve your problem 2.
- in sensor_msgs, create a function to convert a PointCloud2 to a list of those objects (to solve your problem 1)

How does that sound ? Maybe you tried that before ?

**Comment by vrabaud** [comment]
No need for Union actually, there is an example here that shows how to unpack to a namedtuple: https://docs.python.org/2/library/struct.html#examples
That should be trivial to include in read_point.

**Comment by v4hn** [comment]
> No need for Union actually, there is an example here that shows how to unpack to a namedtuple: https://docs.python.org/2/library/struct.html#examples

I'm not very familiar with the struct library. Would these named tuples behave just as `geometry_msgs/Point` (esp. for) publishing?

**Comment by ahcorde** [comment]
This PR is targeting a EOL ROS distro. Feel free to reopen this PR in a newer PR if this is still relevant

**Comment by v4hn** [comment]
This was latter replaced by https://github.com/ros/common_msgs/pull/112 , which was merged upstream. We just forgot to close here. Thanks for cleaning up. :+1:

**Pull request closed without merging**
